const GET_VIDEOGAME_BY_NAME = "GET_VIDEOGAME_BY_NAME";
const SET_PAGE_TO_ONE = "SET_PAGE_TO_ONE";
const FILTER_GENRES = "FILTER_GENRES";
const FILTER_ORIGIN = "FILTER_ORIGIN";
const GET_ALLGAMES = "GET_ALLGAMES";
const ALPHABETH = "ALPHABETH";
const ORDER = "ORDER";
const GET_ALL_GENRES = "GET_ALL_GENRES";
const FILTER = "FILTER";
const SET_FILTER = "SET_FILTER";
const ADD_FILTER = "ADD_FILTER";
const DELETE_FILTER = "DELETE_FILTER";
const RESET_FILTER = "RESET_FILTER";
const SET_ORDER = "SET_ORDER";

export {
  GET_VIDEOGAME_BY_NAME,
  SET_PAGE_TO_ONE,
  FILTER_GENRES,
  FILTER_ORIGIN,
  GET_ALLGAMES,
  ALPHABETH,
  ORDER,
  GET_ALL_GENRES,
  FILTER,
  SET_FILTER,
  ADD_FILTER,
  DELETE_FILTER,
  RESET_FILTER,
  SET_ORDER,
};
